#!/usr/bin/env python3
# Cably Desktop icon family generator: writes cably/icons/src/*.svg.
#
# One mark (a rounded tile in Cably's primary blue carrying a "C" drawn as a
# cable whose two ends are soldered into pads) is reused for every app icon;
# per-editor variants add a small accent-coloured badge, and document icons
# put a scaled mark on a sheet of paper. Nothing here derives from KiCad's
# artwork. Output is deterministic (no timestamps), so the SVGs are committed
# and cably/tests/icons.sh can check the tree against a fresh run.
#
# Copyright (C) 2026 Cably <dev@cably.dev>
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details. You should have received a copy of the GNU General Public
# License along with this program; see LICENSE.GPLv3 in this repository.
import os, sys

# Palette: Cably-pcb/src/index.css  --primary: 210 100% 45%  --accent: 265 80% 55%
PRIMARY, PRIMARY_HI, PRIMARY_LO = "#0073E6", "#0A85FF", "#0061C2"
ACCENT = "#7D30E8"
PAPER, PAPER_EDGE, PAPER_FOLD = "#F7F9FC", "#B9C6D6", "#D6DFEA"
CANVAS = 1024

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  Cably Desktop icon "%s". Generated by cably/icons/make-svgs.py; edit that
  file, not this one. Copyright (C) 2026 Cably <dev@cably.dev>.
  This file is free software: you can redistribute it and/or modify it under
  the terms of the GNU General Public License as published by the Free
  Software Foundation, either version 3 of the License, or (at your option)
  any later version. It is distributed WITHOUT ANY WARRANTY; see LICENSE.GPLv3.
-->
"""

DEFS = f"""  <defs>
    <linearGradient id="tile" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="{PRIMARY_HI}"/>
      <stop offset="0.5" stop-color="{PRIMARY}"/>
      <stop offset="1" stop-color="{PRIMARY_LO}"/>
    </linearGradient>
  </defs>
"""

def mark(indent="  "):
    """The Cably mark filling the 1024 canvas: tile + cable-C + two pads."""
    cx, cy, r = 530, 512, 230
    # ends at +-42 deg: (cx + r cos42, cy +- r sin42)
    ex, ey1, ey2 = 701, 666, 358
    return "\n".join(indent + l for l in [
        f'<rect x="100" y="100" width="824" height="824" rx="184" fill="url(#tile)"/>',
        f'<path d="M {ex} {ey1} A {r} {r} 0 1 1 {ex} {ey2}" fill="none" stroke="#FFFFFF" stroke-width="130" stroke-linecap="round"/>',
        f'<path d="M {ex} {ey1} A {r} {r} 0 1 1 {ex} {ey2}" fill="none" stroke="{PRIMARY}" stroke-width="26" stroke-linecap="round"/>',
        f'<circle cx="{ex}" cy="{ey1}" r="95" fill="#FFFFFF"/><circle cx="{ex}" cy="{ey1}" r="38" fill="{PRIMARY}"/>',
        f'<circle cx="{ex}" cy="{ey2}" r="95" fill="#FFFFFF"/><circle cx="{ex}" cy="{ey2}" r="38" fill="{PRIMARY}"/>',
    ]) + "\n"

# Badge glyphs, drawn in a local 300x300 box, white on the accent tile.
S = 'fill="none" stroke="#FFFFFF" stroke-width="24" stroke-linecap="round" stroke-linejoin="round"'
GLYPHS = {
    "pcb":    [f'<polyline points="70,220 150,220 230,140" {S}/>',
               f'<circle cx="70" cy="220" r="42" fill="#FFFFFF"/><circle cx="70" cy="220" r="16" fill="{ACCENT}"/>',
               f'<circle cx="230" cy="140" r="42" fill="#FFFFFF"/><circle cx="230" cy="140" r="16" fill="{ACCENT}"/>'],
    "fp":     [f'<rect x="{x}" y="{y}" width="72" height="72" rx="14" fill="#FFFFFF"/>'
               for x in (58, 170) for y in (58, 170)],
    "sch":    [f'<polyline points="30,150 70,150 90,105 120,195 150,105 180,195 210,105 230,150 270,150" {S}/>'],
    "sym":    [f'<polygon points="95,70 95,230 240,150" {S}/>',
               f'<path d="M 40 110 H 95 M 40 190 H 95 M 240 150 H 280" {S}/>'],
    "gerber": [f'<polygon points="150,160 250,205 150,250 50,205" {S}/>',
               f'<polygon points="150,105 250,150 150,195 50,150" {S}/>',
               f'<polygon points="150,50 250,95 150,140 50,95" fill="#FFFFFF"/>'],
    "calc":   [f'<polyline points="220,62 82,62 176,150 82,238 220,238" {S.replace("24", "28")}/>'],
    "sheet":  [f'<rect x="50" y="60" width="200" height="180" rx="14" {S}/>',
               f'<path d="M 150 240 V 190 H 250" {S}/>'],
    "img":    [f'<rect x="45" y="60" width="210" height="180" rx="18" {S}/>',
               f'<circle cx="105" cy="115" r="22" fill="#FFFFFF"/>',
               f'<polyline points="62,214 130,150 172,188 202,160 238,206" {S}/>'],
    "cvpcb":  [f'<rect x="60" y="60" width="180" height="180" rx="18" {S}/>',
               f'<rect x="112" y="112" width="76" height="76" rx="10" fill="#FFFFFF"/>'],
}

def badge(kind, x, y, size=300):
    halo = 18
    r = size * 0.24
    g = "\n".join("      " + l for l in GLYPHS[kind])
    k = size / 300.0
    return (f'  <rect x="{x-halo}" y="{y-halo}" width="{size+2*halo}" height="{size+2*halo}" rx="{r+halo}" fill="#FFFFFF"/>\n'
            f'  <rect x="{x}" y="{y}" width="{size}" height="{size}" rx="{r}" fill="{ACCENT}"/>\n'
            f'  <g transform="translate({x} {y}) scale({k:g})">\n{g}\n  </g>\n')

def page():
    # 600x800 sheet with a folded top-right corner
    return "\n".join("  " + l for l in [
        f'<path d="M 248 112 H 622 L 812 302 V 876 a 36 36 0 0 1 -36 36 H 248 a 36 36 0 0 1 -36 -36 V 148 a 36 36 0 0 1 36 -36 Z" fill="{PAPER}" stroke="{PAPER_EDGE}" stroke-width="10" stroke-linejoin="round"/>',
        f'<path d="M 622 112 V 266 a 36 36 0 0 0 36 36 H 812 Z" fill="{PAPER_FOLD}" stroke="{PAPER_EDGE}" stroke-width="10" stroke-linejoin="round"/>',
    ]) + "\n"

def svg(name, body):
    return (HEADER % name +
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{CANVAS}" height="{CANVAS}" viewBox="0 0 {CANVAS} {CANVAS}">\n'
            + DEFS + body + "</svg>\n")

def app_icon(kind=None):
    body = mark()
    if kind:
        body += badge(kind, 620, 620)
    return body

def doc_icon(kind=None):
    body = page()
    body += '  <g transform="translate(512 548) scale(0.46) translate(-512 -512)">\n' + mark("    ") + "  </g>\n"
    if kind:
        body += badge(kind, 630, 660, 270)
    return body

ICONS = {
    "kicad": app_icon(),                 "kicad_doc": doc_icon(),
    "pcbnew": app_icon("pcb"),           "pcbnew_doc": doc_icon("pcb"),
    "fpedit": app_icon("fp"),            "fpedit_doc": doc_icon("fp"),
    "eeschema": app_icon("sch"),         "eeschema_doc": doc_icon("sch"),
    "libedit": app_icon("sym"),          "libedit_doc": doc_icon("sym"),
    "gerbview": app_icon("gerber"),      "gerbview_doc": doc_icon("gerber"),
    "pagelayout_editor": app_icon("sheet"), "pagelayout_editor_doc": doc_icon("sheet"),
    "pcb_calculator": app_icon("calc"),
    "bitmap2component": app_icon("img"),
    "cvpcb": app_icon("cvpcb"),          "cvpcb_doc": doc_icon("cvpcb"),
}

if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(os.path.abspath(__file__)), "src")
    os.makedirs(out, exist_ok=True)
    for name, body in ICONS.items():
        with open(os.path.join(out, name + ".svg"), "w") as f:
            f.write(svg(name, body))
    print(f"wrote {len(ICONS)} SVGs to {out}")
